# Generated by Django 2.2.6 on 2019-10-16 08:35

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='biography',
            field=models.CharField(blank=True, max_length=150, verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, upload_to=account.models.upload_location),
        ),
    ]
