# Generated by Django 2.2.6 on 2019-10-20 09:05

import account.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191016_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='account',
            name='picture',
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.CharField(blank=True, max_length=150, verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not-specified', 'Not Specified')], max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-pic.jpg', upload_to=account.models.upload_location),
        ),
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last login'),
        ),
    ]
