# Generated by Django 2.2.6 on 2019-10-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='posts',
        ),
    ]
