# Generated by Django 2.2.6 on 2019-10-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_account_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='account',
            name='following',
        ),
    ]
