# Generated by Django 2.2.6 on 2019-10-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191016_1615'),
        ('account', '0014_auto_20191020_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='posts',
            field=models.ManyToManyField(blank=True, to='post.Post'),
        ),
    ]
