# Generated by Django 2.2.6 on 2019-10-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20191020_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('public', 'Public Account'), ('private', 'Private_Account')], default='public', max_length=80),
        ),
    ]
