# Generated by Django 2.2.6 on 2019-10-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='request',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('public', 'Public_Account'), ('private', 'Private_Account')], default='public', max_length=80),
        ),
    ]
