# Generated by Django 2.2.6 on 2019-11-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20191107_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('public', 'Public_Account'), ('private', 'Private_Account')], default='public', max_length=80),
        ),
    ]
