# Generated by Django 2.2.6 on 2019-11-29 17:18

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20191129_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-pic.jpg', upload_to=account.models.upload_location),
        ),
    ]
