# Generated by Django 2.2.6 on 2019-11-30 12:26

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20191129_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/instacloud252/image/upload/v1575045629/default-pic_ljw66l.jpg', upload_to=account.models.upload_location),
        ),
    ]
