# Generated by Django 2.2.6 on 2019-10-27 06:00

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20191023_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=post.models.generate_id, max_length=11, unique=True),
        ),
    ]
