# Generated by Django 2.2.6 on 2019-12-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
