# Generated by Django 2.2.6 on 2019-10-24 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20191023_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.AddField(
            model_name='chat',
            name='user01',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user01_chat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='user02',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user02_chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
