# Generated by Django 2.2.6 on 2019-10-24 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20191024_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
