# Generated by Django 2.2.6 on 2019-10-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20191027_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='deletefor',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
