# Generated by Django 2.2.6 on 2019-10-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_chat_deletefor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='deletefor',
            field=models.IntegerField(blank=True, choices=[(0, 'displayed to both'), (1, 'DELETED for user01'), (2, 'DELETED for user02')], default=0),
        ),
    ]
