# Generated by Django 2.2.6 on 2019-12-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20191030_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='deletefor',
            field=models.IntegerField(blank=True, choices=[(1, 'DELETED for user01'), (2, 'DELETED for user02')], default=0, null=True),
        ),
    ]
