# Generated by Django 2.2.6 on 2019-11-02 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(choices=[('following', 'started following you'), ('like', 'liked your photo')], max_length=100)),
                ('notification_type', models.CharField(choices=[('request', 'REQUEST_NOTIFICATION'), ('following', 'FOLLOWING_NOTIFICATION'), ('like', 'LIKE_NOTIFICATION')], max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('notification_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifcation_by_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifcation_for_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
