# Generated by Django 2.2.6 on 2019-11-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.CharField(choices=[('following', 'started following you'), ('like', 'liked your photo')], max_length=100, null=True),
        ),
    ]
