# Generated by Django 2.2.6 on 2019-11-09 17:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20191028_2250'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0003_notifications_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
